# Generated by Django 2.1.15 on 2020-12-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20201221_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='meetup_link',
            field=models.URLField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='picture',
            field=models.ImageField(blank=True, upload_to='chapters/pictures'),
        ),
    ]
