# Generated by Django 2.1.15 on 2020-12-28 06:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20201228_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='picture',
        ),
        migrations.AddField(
            model_name='chapter',
            name='picture_src',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='chapters/cover', verbose_name='picture'),
        ),
    ]
