# Generated by Django 2.1.15 on 2021-02-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20201228_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_email_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
