# Generated by Django 2.1.15 on 2021-01-10 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20201228_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('', 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Prefer Not To Say', 'Prefer Not to Say')], default=('', 'Gender'), max_length=25)),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('status', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('skills', models.CharField(blank=True, default='', max_length=350, null=True)),
                ('pp_src', models.ImageField(blank=True, upload_to='users/profile_pictures', verbose_name='Profile Picture')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Facebook Proifle Link')),
                ('tw_link', models.URLField(blank=True, null=True, verbose_name='Twitter Proifle Link')),
                ('ig_link', models.URLField(blank=True, null=True, verbose_name='Instagram Proifle Link')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('ASRG_member', 'ASRG_member'), ('ASRG_global_lead', 'ASRG_global_lead'), ('ASRG_global_admin', 'ASRG_global_admin'), ('ASRG_sponsor_L1', 'ASRG_sponsor_L1'), ('ASRG_sponsor_L2', 'ASRG_sponsor_L2'), ('ASRG_sponsor_L3', 'ASRG_sponsor_L3'), ('ASRG_asip_contributor', 'ASRG_asip_contributor')],
            },
        ),
    ]
