# Generated by Django 2.1.15 on 2021-02-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chapter',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.Chapter'),
        ),
    ]
