# Generated by Django 2.1.15 on 2021-02-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20210210_1827'),
        ('authentication', '0014_user_verification_email_sent_date'),
    ]

    operations = [
    ]
