# Generated by Django 2.2.19 on 2021-03-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_merge_20210212_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'permissions': [], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
