# Generated by Django 2.2.20 on 2021-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20210413_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Location email address'),
        ),
    ]
