# Generated by Django 2.2.20 on 2021-04-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_chapter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Location email address'),
        ),
    ]
