default_language_version:
    python: python3
repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      exclude: migrations
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      args: [--exit-zero]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: debug-statements
-   repo: local
    hooks:
    - id: check-migrations
      name: check-migrations
      # entry: python3 django_app/manage.py makemigrations --check --dry-run
      entry: docker exec asrg-app python manage.py makemigrations --check --dry-run
      language: system
      types: [python]
      files: models.*\.py$
      pass_filenames: false
