version: '3'
services:
  asrg-db:
    container_name: asrg-postgres
    restart: unless-stopped
    image: postgres:12.4
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/asrg/
    volumes:
      - ./db_backup/:/var/lib/postgresql/data
    networks:
      - db_network
  asrg-app:
    container_name: asrg-app
    restart: unless-stopped
    command: /bin/bash /opt/code/docker-entrypoint.sh
    volumes:
      - ./django_app/:/opt/code
    env_file: ./.env
    environment:
      - WAIT_HOSTS=asrg-db:5432
    build: .
    ports:
      - "${ASRG_APP_PORT}:5005"
    networks:
      - web_network
      - db_network
    depends_on:
      - asrg-db
  cms:
    container_name: asrg-cms
    restart: unless-stopped
    image: "vimagick/django-cms"
    ports:
      - "8000:80"
  nginx:
    container_name: asrg-nginx
    restart: unless-stopped
    image: "nginx:1.17.2"
    env_file: ./.env
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/asrg.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - "${NGINX_HTTP_PORT}:8081"
      - "${NGINX_HTTPS_PORT}:4431"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./django_app/asrg/media:/opt/asrg/media
      # - ${CERTS_PATH}:/etc/nginx/certs
    networks:
      - web_network
    depends_on: 
      - asrg-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  db_data: {}
