# Generated by Django 2.1.15 on 2020-08-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='chapter',
        ),
    ]
