# Generated by Django 2.1.15 on 2020-10-04 10:24

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200910_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fb_link',
            field=models.URLField(blank=True, verbose_name='Facebook Proifle Link'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('', 'Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Prefer Not To Say', 'Prefer Not to Say')], default=('', 'Gender'), max_length=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ig_link',
            field=models.URLField(blank=True, verbose_name='Instagram Proifle Link'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pp_src',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='users/profile_pictures', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tw_link',
            field=models.URLField(blank=True, verbose_name='Twitter Proifle Link'),
        ),
    ]
