TIMEZONES = (
     ('UTC−12', 'UTC−12 - Baker Island Time(BIT)'),
    ('UTC−12', 'UTC−12 - International Day Line West time zone(IDLW)'),
    ('UTC−11', 'UTC−11 - Niue Time(NUT)'),
    ('UTC−11', 'UTC−11 - Samoa Standard Time(SST)'),
    ('UTC−10', 'UTC−10 - Cook Island Time(CKT)'),
    ('UTC−10', 'UTC−10 - Hawaii–Aleutian Standard Time(HST)'),
    ('UTC−10', 'UTC−10 - Samoa Daylight Time(SDT)'),
    ('UTC−10', 'UTC−10 - Tahiti Time(TAHT)'),
    ('UTC−09:30', 'UTC−09:30 - Marquesas Islands Time(MART)'),
    ('UTC−09:30', 'UTC−09:30 - Marquesas Islands Time(MIT)'),
    ('UTC−09', 'UTC−09 - Alaska Standard Time(AKST)'),
    ('UTC−09', 'UTC−09 - Gambier Islands Time(GAMT)'),
    ('UTC−09', 'UTC−09 - Gambier Island Time(GIT)'),
    ('UTC−09', 'UTC−09 - Hawaii–Aleutian Daylight Time(HDT)'),
    ('UTC−08', 'UTC−08 - Alaska Daylight Time(AKDT)'),
    ('UTC−08', 'UTC−08 - Clipperton Island Standard Time(CIST)'),
    ('UTC−08', 'UTC−08 - Pacific Standard Time(North America)(PST)'),
    ('UTC−07', 'UTC−07 - Mountain Standard Time(North America)(MST)'),
    ('UTC−07', 'UTC−07 - Pacific Daylight Time(North America)(PDT)'),
    ('UTC-06|UTC-05', 'UTC-06|UTC-05 - Central Time(CT)'),
    ('UTC−06', 'UTC−06 - Central Standard Time(North America)(CST)'),
    ('UTC−06', 'UTC−06 - Easter Island Standard Time(EAST)'),
    ('UTC−06', 'UTC−06 - Galápagos Time(GALT)'),
    ('UTC−06', 'UTC−06 - Mountain Daylight Time(North America)(MDT)'),
    ('UTC−05', 'UTC−05 - Acre Time(ACT)'),
    ('UTC−05', 'UTC−05 - Central Daylight Time(North America)(CDT)'),
    ('UTC−05', 'UTC−05 - Colombia Time(COT)'),
    ('UTC−05', 'UTC−05 - Cuba Standard Time(CST)'),
    ('UTC−05', 'UTC−05 - Easter Island Summer Time(EASST)'),
    ('UTC−05', 'UTC−05 - Ecuador Time(ECT)'),
    ('UTC−05', 'UTC−05 - Eastern Standard Time (North America)(EST)'),
    ('UTC−05', 'UTC−05 - Peru Time(PET)'),
    ('UTC−04', 'UTC−04 - Amazon Time(Brazil)(AMT)'),
    ('UTC−04', 'UTC−04 - Atlantic Standard Time(AST)'),
    ('UTC−04', 'UTC−04 - Bolivia Time(BOT)'),
    ('UTC−04', 'UTC−04 - Cuba Daylight Time(CDT)'),
    ('UTC−04', 'UTC−04 - Chile Standard Time(CLT)'),
    ('UTC−04', 'UTC−04 - Colombia Summer Time(COST)'),
    ('UTC−04', 'UTC−04 - Eastern Caribbean Time(does not recognise DST)(ECT)'),
    ('UTC−04', 'UTC−04 - Eastern Daylight Time(North America)(EDT)'),
    ('UTC−04', 'UTC−04 - Falkland Islands Time(FKT)'),
    ('UTC−04', 'UTC−04 - Guyana Time(GYT)'),
    ('UTC−04', 'UTC−04 - Paraguay Time(PYT)'),
    ('UTC−04', 'UTC−04 - Venezuelan Standard Time(VET)'),
    ('UTC−03:30', 'UTC−03:30 - Newfoundland Standard Time(NST)'),
    ('UTC−03:30', 'UTC−03:30 - Newfoundland Time(NT)'),
    ('UTC−03', 'UTC−03 - Atlantic Daylight Time(ADT)'),
    ('UTC−03', 'UTC−03 - Amazon Summer Time(Brazil)(AMST)'),
    ('UTC−03', 'UTC−03 - Argentina Time(ART)'),
    ('UTC−03', 'UTC−03 - Brasília Time(BRT)'),
    ('UTC−03', 'UTC−03 - Chile Summer Time(CLST)'),
    ('UTC−03', 'UTC−03 - Falkland Islands Summer Time(FKST)'),
    ('UTC−03', 'UTC−03 - French Guiana Time(GFT)'),
    ('UTC−03', 'UTC−03 - Saint Pierre and Miquelon Standard Time(PMST)'),
    ('UTC−03', 'UTC−03 - Paraguay Summer Time(PYST)'),
    ('UTC−03', 'UTC−03 - Rothera Research Station Time(ROTT)'),
    ('UTC−03', 'UTC−03 - Suriname Time(SRT)'),
    ('UTC−03', 'UTC−03 - Uruguay Standard Time(UYT)'),
    ('UTC−03', 'UTC−03 - West Greenland Time(WGT)'),
    ('UTC−02:30', 'UTC−02:30 - Newfoundland Daylight Time(NDT)'),
    ('UTC−02', 'UTC−02 - Brasília Summer Time(BRST)'),
    ('UTC−02', 'UTC−02 - Fernando de Noronha Time(FNT)'),
    ('UTC−02', 'UTC−02 - South Georgia and the South Sandwich Islands Time(GST)'),
    ('UTC−02', 'UTC−02 - Saint Pierre and Miquelon Daylight Time(PMDT)'),
    ('UTC−02', 'UTC−02 - Uruguay Summer Time(UYST)'),
    ('UTC−02', 'UTC−02 - West Greenland Summer Time(WGST)'),
    ('UTC−01', 'UTC−01 - Azores Standard Time(AZOT)'),
    ('UTC−01', 'UTC−01 - Cape Verde Time(CVT)'),
    ('UTC−01', 'UTC−01 - Eastern Greenland Time(EGT)'),
    ('UTC±00', 'UTC±00 - Azores Summer Time(AZOST)'),
    ('UTC±00', 'UTC±00 - Eastern Greenland Summer Time(EGST)'),
    ('UTC±00', 'UTC±00 - Greenwich Mean Time(GMT)'),
    ('UTC±00', 'UTC±00 - Coordinated Universal Time(UTC)'),
    ('UTC±00', 'UTC±00 - Western European Time(WET)'),
    ('UTC+01', 'UTC+01 - Central European Time(CET)'),
    ('UTC+01', 'UTC+01 - AIX-specific equivalent ofCentral European Time 1(DFT)'),
    ('UTC+01', 'UTC+01 - Irish Standard Time(IST)'),
    ('UTC+01', 'UTC+01 - Middle European TimeSame zone as CET(MET)'),
    ('UTC+01', 'UTC+01 - West Africa Time(WAT)'),
    ('UTC+01', 'UTC+01 - Western European Summer Time(WEST)'),
    ('UTC+02', 'UTC+02 - Central Africa Time(CAT)'),
    ('UTC+02', 'UTC+02 - Central European Summer Time(Cf. HAEC)(CEST)'),
    ('UTC+02', 'UTC+02 - Eastern European Time(EET)'),
    ('UTC+02', 'UTC+02 - "Heure Avancée dEurope CentraleFrench-language name for CEST"(HAEC)'),
    ('UTC+02', 'UTC+02 - Israel Standard Time(IST)'),
    ('UTC+02', 'UTC+02 - Kaliningrad Time(KALT)'),
    ('UTC+02', 'UTC+02 - Middle European Summer TimeSame zone as CEST(MEST)'),
    ('UTC+02', 'UTC+02 - South African Standard Time(SAST)'),
    ('UTC+02', 'UTC+02 - West Africa Summer Time(WAST)'),
    ('UTC+03', 'UTC+03 - Arabia Standard Time(AST)'),
    ('UTC+03', 'UTC+03 - East Africa Time(EAT)'),
    ('UTC+03', 'UTC+03 - Eastern European Summer Time(EEST)'),
    ('UTC+03', 'UTC+03 - Further-eastern European Time(FET)'),
    ('UTC+03', 'UTC+03 - Israel Daylight Time(IDT)'),
    ('UTC+03', 'UTC+03 - Indian Ocean Time(IOT)'),
    ('UTC+03', 'UTC+03 - Moscow Time(MSK)'),
    ('UTC+03', 'UTC+03 - Showa Station Time(SYOT)'),
    ('UTC+03', 'UTC+03 - Turkey Time(TRT)'),
    ('UTC+03:30', 'UTC+03:30 - Iran Standard Time(IRST)'),
    ('UTC+04', 'UTC+04 - Armenia Time(AMT)'),
    ('UTC+04', 'UTC+04 - Azerbaijan Time(AZT)'),
    ('UTC+04', 'UTC+04 - Georgia Standard Time(GET)'),
    ('UTC+04', 'UTC+04 - Gulf Standard Time(GST)'),
    ('UTC+04', 'UTC+04 - Mauritius Time(MUT)'),
    ('UTC+04', 'UTC+04 - Réunion Time(RET)'),
    ('UTC+04', 'UTC+04 - Samara Time(SAMT)'),
    ('UTC+04', 'UTC+04 - Seychelles Time(SCT)'),
    ('UTC+04', 'UTC+04 - Volgograd Time(VOLT)'),
    ('UTC+04:30', 'UTC+04:30 - Afghanistan Time(AFT)'),
    ('UTC+04:30', 'UTC+04:30 - Iran Daylight Time(IRDT)'),
    ('UTC+05', 'UTC+05 - Aqtobe Time(AQTT)'),
    ('UTC+05', 'UTC+05 - Heard and McDonald IslandsTime(HMT)'),
    ('UTC+05', 'UTC+05 - Mawson Station Time(MAWT)'),
    ('UTC+05', 'UTC+05 - Maldives Time(MVT)'),
    ('UTC+05', 'UTC+05 - Oral Time(ORAT)'),
    ('UTC+05', 'UTC+05 - Pakistan Standard Time(PKT)'),
    ('UTC+05', 'UTC+05 - French Southern and Antarctic Time(TFT)'),
    ('UTC+05', 'UTC+05 - Tajikistan Time(TJT)'),
    ('UTC+05', 'UTC+05 - Turkmenistan Time(TMT)'),
    ('UTC+05', 'UTC+05 - Uzbekistan Time(UZT)'),
    ('UTC+05', 'UTC+05 - Yekaterinburg Time(YEKT)'),
    ('UTC+05:30', 'UTC+05:30 - Indian Standard Time(IST)'),
    ('UTC+05:30', 'UTC+05:30 - Sri Lanka Standard Time(SLST)'),
    ('UTC+05:45', 'UTC+05:45 - Nepal Time(NPT)'),
    ('UTC+06', 'UTC+06 - Alma-Ata Time(ALMT)'),
    ('UTC+06', 'UTC+06 - British Indian Ocean Time(BIOT)'),
    ('UTC+06', 'UTC+06 - Bangladesh Standard Time(BST)'),
    ('UTC+06', 'UTC+06 - Bhutan Time(BTT)'),
    ('UTC+06', 'UTC+06 - Kyrgyzstan Time(KGT)'),
    ('UTC+06', 'UTC+06 - Omsk Time(OMST)'),
    ('UTC+06', 'UTC+06 - Vostok Station Time(VOST)'),
    ('UTC+06:30', 'UTC+06:30 - Cocos Islands Time(CCT)'),
    ('UTC+06:30', 'UTC+06:30 - Myanmar Standard Time(MMT)'),
    ('UTC+06:30–UTC+09', 'UTC+06:30–UTC+09 - ASEAN Common Time(unofficial)(ACT)'),
    ('UTC+07', 'UTC+07 - Christmas Island Time(CXT)'),
    ('UTC+07', 'UTC+07 - Davis Time(DAVT)'),
    ('UTC+07', 'UTC+07 - Hovd Time(HOVT)'),
    ('UTC+07', 'UTC+07 - Indochina Time(ICT)'),
    ('UTC+07', 'UTC+07 - Krasnoyarsk Time(KRAT)'),
    ('UTC+07', 'UTC+07 - Novosibirsk Time(NOVT)'),
    ('UTC+07', 'UTC+07 - Thailand Standard Time(THA)'),
    ('UTC+07', 'UTC+07 - Western Indonesian Time(WIB)'),
    ('UTC+08', 'UTC+08 - Australian Western Standard Time(AWST)'),
    ('UTC+08', 'UTC+08 - Brunei Time(BDT)'),
    ('UTC+08', 'UTC+08 - Choibalsan Standard Time(CHOT)'),
    ('UTC+08', 'UTC+08 - Central Indonesia Time(WITA)'),
    ('UTC+08', 'UTC+08 - China Standard Time(CST)'),
    ('UTC+08', 'UTC+08 - Hong Kong Time(HKT)'),
    ('UTC+08', 'UTC+08 - Hovd Summer Time(not used from 2017-present)(HOVST)'),
    ('UTC+08', 'UTC+08 - Irkutsk Time(IRKT)'),
    ('UTC+08', 'UTC+08 - Malaysia Standard Time(MST)'),
    ('UTC+08', 'UTC+08 - Malaysia Time(MYT)'),
    ('UTC+08', 'UTC+08 - Philippine Time(PHT)'),
    ('UTC+08', 'UTC+08 - Philippine Standard Time(PST)'),
    ('UTC+08', 'UTC+08 - Singapore Time(SGT)'),
    ('UTC+08', 'UTC+08 - Singapore Standard Time(SST)'),
    ('UTC+08', 'UTC+08 - Ulaanbaatar Standard Time(ULAT)'),
    ('UTC+08', 'UTC+08 - Western Standard Time(WST)'),
    ('UTC+08:45', 'UTC+08:45 - Australian Central Western Standard Time(unofficial)(ACWST)'),
    ('UTC+08:45', 'UTC+08:45 - Central Western Standard Time(Australia) unofficial(CWST)'),
    ('UTC+09', 'UTC+09 - Choibalsan Summer Time(CHOST)'),
    ('UTC+09', 'UTC+09 - Eastern Indonesian Time(WIT)'),
    ('UTC+09', 'UTC+09 - Japan Standard Time(JST)'),
    ('UTC+09', 'UTC+09 - Korea Standard Time(KST)'),
    ('UTC+09', 'UTC+09 - Timor Leste Time(TLT)'),
    ('UTC+09', 'UTC+09 - Ulaanbaatar Summer Time(ULAST)'),
    ('UTC+09', 'UTC+09 - Yakutsk Time(YAKT)'),
    ('UTC+09:30', 'UTC+09:30 - Australian Central Standard Time(ACST)'),
    ('UTC+10', 'UTC+10 - Australian Eastern Standard Time(AEST)'),
    ('UTC+10', 'UTC+10 - Chamorro Standard Time(CHST)'),
    ('UTC+10', 'UTC+10 - Chuuk Time(CHUT)'),
    ('UTC+10', 'UTC+10 - "Dumont dUrville Time"(DDUT)'),
    ('UTC+10', 'UTC+10 - Papua New Guinea Time(PGT)'),
    ('UTC+10', 'UTC+10 - Vladivostok Time(VLAT)'),
    ('UTC+10|UTC+11', 'UTC+10|UTC+11 - Australian Eastern Time(AET)'),
    ('UTC+10:30', 'UTC+10:30 - Australian Central Daylight Saving Time(ACDT)'),
    ('UTC+10:30', 'UTC+10:30 - Lord Howe Standard Time(LHST)'),
    ('UTC+11', 'UTC+11 - Australian Eastern Daylight Saving Time(AEDT)'),
    ('UTC+11', 'UTC+11 - Bougainville Standard Time(BST)'),
    ('UTC+11', 'UTC+11 - Kosrae Time(KOST)'),
    ('UTC+11', 'UTC+11 - Lord Howe Summer Time(LHST)'),
    ('UTC+11', 'UTC+11 - Macquarie Island Station Time(MIST)'),
    ('UTC+11', 'UTC+11 - New Caledonia Time(NCT)'),
    ('UTC+11', 'UTC+11 - Norfolk Island Time(NFT)'),
    ('UTC+11', 'UTC+11 - Pohnpei Standard Time(PONT)'),
    ('UTC+11', 'UTC+11 - Sakhalin Island Time(SAKT)'),
    ('UTC+11', 'UTC+11 - Solomon Islands Time(SBT)'),
    ('UTC+11', 'UTC+11 - Srednekolymsk Time(SRET)'),
    ('UTC+11', 'UTC+11 - VanuatuTime(VUT)'),
    ('UTC+12', 'UTC+12 - Anadyr Time(ANAT)'),
    ('UTC+12', 'UTC+12 - Fiji Time(FJT)'),
    ('UTC+12', 'UTC+12 - Gilbert Island Time(GILT)'),
    ('UTC+12', 'UTC+12 - Magadan Time(MAGT)'),
    ('UTC+12', 'UTC+12 - Marshall Islands Time(MHT)'),
    ('UTC+12', 'UTC+12 - New Zealand Standard Time(NZST)'),
    ('UTC+12', 'UTC+12 - Kamchatka Time(PETT)'),
    ('UTC+12', 'UTC+12 - Tuvalu Time(TVT)'),
    ('UTC+12', 'UTC+12 - Wake Island Time(WAKT)'),
    ('UTC+12:45', 'UTC+12:45 - Chatham Standard Time(CHAST)'),
    ('UTC+13', 'UTC+13 - New Zealand Daylight Time(NZDT)'),
    ('UTC+13', 'UTC+13 - Phoenix Island Time(PHOT)'),
    ('UTC+13', 'UTC+13 - Tokelau Time(TKT)'),
    ('UTC+13', 'UTC+13 - Tonga Time(TOT)'),
    ('UTC+13:45', 'UTC+13:45 - Chatham Daylight Time(CHADT)'),
    ('UTC+14', 'UTC+14 - Line IslandsTime(LINT)'),
 )