# Generated by Django 2.1.15 on 2020-11-11 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='pres_com_log',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='events/company_logos', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pres_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='events/presenters', verbose_name='Presenter Picture'),
        ),
    ]
