# Generated by Django 2.1.15 on 2020-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201004_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_link',
            field=models.URLField(blank=True, verbose_name='Job Posting Link'),
        ),
    ]
