# Generated by Django 2.2.20 on 2021-04-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_app_counterconfig', serialize=False, to='cms.CMSPlugin')),
                ('member_offset', models.IntegerField(default=5657)),
                ('locations_offset', models.IntegerField(default=0)),
                ('meetings_offset', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
