# Generated by Django 2.1.15 on 2020-10-04 10:24

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('announcement', models.TextField(max_length=300)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('img', imagekit.models.fields.ProcessedImageField(upload_to='contributors', verbose_name='Image')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
