# Generated by Django 2.1.15 on 2020-11-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lead',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='location',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
    ]
