# Generated by Django 2.2.19 on 2021-03-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20201112_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
