# Generated by Django 2.1.15 on 2020-08-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='chapter',
        ),
    ]
