# Generated by Django 2.1.15 on 2020-08-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_auto_20200819_2016'),
        ('app', '0003_remove_userprofile_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chapter',
            field=models.ManyToManyField(related_name='profile', to='authentication.Chapter'),
        ),
    ]
