# Generated by Django 2.1.15 on 2020-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201004_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fb_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Proifle Link'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ig_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Proifle Link'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pp_src',
            field=models.ImageField(blank=True, upload_to='users/profile_pictures', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.CharField(blank=True, default='', max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tw_link',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter Proifle Link'),
        ),
    ]
