# Generated by Django 2.2.20 on 2021-05-12 17:33

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='training/logo', verbose_name='Logo'),
        ),
    ]
