# Generated by Django 2.2.20 on 2021-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='duration',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='training',
            name='costs',
            field=models.CharField(max_length=12),
        ),
    ]
