# Generated by Django 2.2.20 on 2021-05-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_populate_inintial_data'),
        ('training', '0002_auto_20210512_1733'),
    ]

    operations = [
    ]
