# Generated by Django 2.2.20 on 2021-06-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_language'),
        ('training', '0006_populate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='language',
            field=models.ManyToManyField(null=True, to='authentication.Language'),
        ),
    ]
