# Generated by Django 2.2.20 on 2021-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_training_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='language',
            field=models.ManyToManyField(blank=True, to='authentication.Language'),
        ),
    ]
