# Generated by Django 2.2.19 on 2021-03-03 16:36

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='sponsors/logos', verbose_name='Company Logo')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(verbose_name='Bio')),
            ],
        ),
    ]
