# Generated by Django 2.2.19 on 2021-03-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='General email address'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('not-active', 'Not active')], default='not-active', max_length=20),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sponsor website'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(),
        ),
    ]
