# Generated by Django 2.1.15 on 2021-01-19 20:41

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('img', imagekit.models.fields.ProcessedImageField(upload_to='contributors', verbose_name='Image')),
            ],
        ),
    ]
