TIMEZONES = (
      ('Baker Island Time(UTC−12)', 'UTC−12 - Baker Island Time(BIT)'),
      ('International Day Line West time zone(UTC−12)', 'UTC−12 - International Day Line West time zone(IDLW)'),
      ('Niue Time(UTC−11)', 'UTC−11 - Niue Time(NUT)'),
      ('Samoa Standard Time(UTC−11)', 'UTC−11 - Samoa Standard Time(SST)'),
      ('Cook Island Time(UTC−10)', 'UTC−10 - Cook Island Time(CKT)'),
      ('Hawaii–Aleutian Standard Time(UTC−10)', 'UTC−10 - Hawaii–Aleutian Standard Time(HST)'),
      ('Samoa Daylight Time(UTC−10)', 'UTC−10 - Samoa Daylight Time(SDT)'),
      ('Tahiti Time(UTC−10)', 'UTC−10 - Tahiti Time(TAHT)'),
      ('Marquesas Islands Time(UTC−09:30)', 'UTC−09:30 - Marquesas Islands Time(MART)'),
      ('Marquesas Islands Time(UTC−09:30)', 'UTC−09:30 - Marquesas Islands Time(MIT)'),
      ('Alaska Standard Time(UTC−09)', 'UTC−09 - Alaska Standard Time(AKST)'),
      ('Gambier Islands Time(UTC−09)', 'UTC−09 - Gambier Islands Time(GAMT)'),
      ('Gambier Island Time(UTC−09)', 'UTC−09 - Gambier Island Time(GIT)'),
      ('Hawaii–Aleutian Daylight Time(UTC−09)', 'UTC−09 - Hawaii–Aleutian Daylight Time(HDT)'),
      ('Alaska Daylight Time(UTC−08)', 'UTC−08 - Alaska Daylight Time(AKDT)'),
      ('Clipperton Island Standard Time(UTC−08)', 'UTC−08 - Clipperton Island Standard Time(CIST)'),
      ('Pacific Standard Time (North America)(UTC−08)', 'UTC−08 - Pacific Standard Time (North America)(PST)'),
      ('Mountain Standard Time (North America)(UTC−07)', 'UTC−07 - Mountain Standard Time (North America)(MST)'),
      ('Pacific Daylight Time (North America)(UTC−07)', 'UTC−07 - Pacific Daylight Time (North America)(PDT)'),
      ('Central Time(UTC-06|UTC-05)', 'UTC-06|UTC-05 - Central Time(CT)'),
      ('Central Standard Time (North America)(UTC−06)', 'UTC−06 - Central Standard Time (North America)(CST)'),
      ('Easter Island Standard Time(UTC−06)', 'UTC−06 - Easter Island Standard Time(EAST)'),
      ('Galápagos Time(UTC−06)', 'UTC−06 - Galápagos Time(GALT)'),
      ('Mountain Daylight Time (North America)(UTC−06)', 'UTC−06 - Mountain Daylight Time (North America)(MDT)'),
      ('Acre Time(UTC−05)', 'UTC−05 - Acre Time(ACT)'),
      ('Central Daylight Time (North America)(UTC−05)', 'UTC−05 - Central Daylight Time (North America)(CDT)'),
      ('Colombia Time(UTC−05)', 'UTC−05 - Colombia Time(COT)'),
      ('Cuba Standard Time(UTC−05)', 'UTC−05 - Cuba Standard Time(CST)'),
      ('Easter Island Summer Time(UTC−05)', 'UTC−05 - Easter Island Summer Time(EASST)'),
      ('Ecuador Time(UTC−05)', 'UTC−05 - Ecuador Time(ECT)'),
      ('Eastern Standard Time (North America)(UTC−05)', 'UTC−05 - Eastern Standard Time (North America)(EST)'),
      ('Peru Time(UTC−05)', 'UTC−05 - Peru Time(PET)'),
      ('Amazon Time (Brazil)(UTC−04)', 'UTC−04 - Amazon Time (Brazil)(AMT)'),
      ('Atlantic Standard Time(UTC−04)', 'UTC−04 - Atlantic Standard Time(AST)'),
      ('Bolivia Time(UTC−04)', 'UTC−04 - Bolivia Time(BOT)'),
      ('Cuba Daylight Time(UTC−04)', 'UTC−04 - Cuba Daylight Time(CDT)'),
      ('Chile Standard Time(UTC−04)', 'UTC−04 - Chile Standard Time(CLT)'),
      ('Colombia Summer Time(UTC−04)', 'UTC−04 - Colombia Summer Time(COST)'),
      ('Eastern Caribbean Time(UTC−04)', 'UTC−04 - Eastern Caribbean Time(ECT)'),
      ('Eastern Daylight Time (North America)(UTC−04)', 'UTC−04 - Eastern Daylight Time (North America)(EDT)'),
      ('Falkland Islands Time(UTC−04)', 'UTC−04 - Falkland Islands Time(FKT)'),
      ('Guyana Time(UTC−04)', 'UTC−04 - Guyana Time(GYT)'),
      ('Paraguay Time(UTC−04)', 'UTC−04 - Paraguay Time(PYT)'),
      ('Venezuelan Standard Time(UTC−04)', 'UTC−04 - Venezuelan Standard Time(VET)'),
      ('Newfoundland Standard Time(UTC−03:30)', 'UTC−03:30 - Newfoundland Standard Time(NST)'),
      ('Newfoundland Time(UTC−03:30)', 'UTC−03:30 - Newfoundland Time(NT)'),
      ('Atlantic Daylight Time(UTC−03)', 'UTC−03 - Atlantic Daylight Time(ADT)'),
      ('Amazon Summer Time (Brazil)(UTC−03)', 'UTC−03 - Amazon Summer Time (Brazil)(AMST)'),
      ('Argentina Time(UTC−03)', 'UTC−03 - Argentina Time(ART)'),
      ('Brasília Time(UTC−03)', 'UTC−03 - Brasília Time(BRT)'),
      ('Chile Summer Time(UTC−03)', 'UTC−03 - Chile Summer Time(CLST)'),
      ('Falkland Islands Summer Time(UTC−03)', 'UTC−03 - Falkland Islands Summer Time(FKST)'),
      ('French Guiana Time(UTC−03)', 'UTC−03 - French Guiana Time(GFT)'),
      ('Saint Pierre and Miquelon Standard Time(UTC−03)', 'UTC−03 - Saint Pierre and Miquelon Standard Time(PMST)'),
      ('Paraguay Summer Time(UTC−03)', 'UTC−03 - Paraguay Summer Time(PYST)'),
      ('Rothera Research Station Time(UTC−03)', 'UTC−03 - Rothera Research Station Time(ROTT)'),
      ('Suriname Time(UTC−03)', 'UTC−03 - Suriname Time(SRT)'),
      ('Uruguay Standard Time(UTC−03)', 'UTC−03 - Uruguay Standard Time(UYT)'),
      ('West Greenland Time(UTC−03)', 'UTC−03 - West Greenland Time(WGT)'),
      ('Newfoundland Daylight Time(UTC−02:30)', 'UTC−02:30 - Newfoundland Daylight Time(NDT)'),
      ('Brasília Summer Time(UTC−02)', 'UTC−02 - Brasília Summer Time(BRST)'),
      ('Fernando de Noronha Time(UTC−02)', 'UTC−02 - Fernando de Noronha Time(FNT)'),
      ('South Georgia and the South Sandwich Islands Time(UTC−02)', 'UTC−02 - South Georgia and the South Sandwich Islands Time(GST)'),
      ('Saint Pierre and Miquelon Daylight Time(UTC−02)', 'UTC−02 - Saint Pierre and Miquelon Daylight Time(PMDT)'),
      ('Uruguay Summer Time(UTC−02)', 'UTC−02 - Uruguay Summer Time(UYST)'),
      ('West Greenland Summer Time(UTC−02)', 'UTC−02 - West Greenland Summer Time(WGST)'),
      ('Azores Standard Time(UTC−01)', 'UTC−01 - Azores Standard Time(AZOT)'),
      ('Cape Verde Time(UTC−01)', 'UTC−01 - Cape Verde Time(CVT)'),
      ('Eastern Greenland Time(UTC−01)', 'UTC−01 - Eastern Greenland Time(EGT)'),
      ('Azores Summer Time(UTC±00)', 'UTC±00 - Azores Summer Time(AZOST)'),
      ('Eastern Greenland Summer Time(UTC±00)', 'UTC±00 - Eastern Greenland Summer Time(EGST)'),
      ('Greenwich Mean Time(UTC±00)', 'UTC±00 - Greenwich Mean Time(GMT)'),
      ('Coordinated Universal Time(UTC±00)', 'UTC±00 - Coordinated Universal Time(UTC)'),
      ('Western European Time(UTC±00)', 'UTC±00 - Western European Time(WET)'),
      ('Central European Time(UTC+01)', 'UTC+01 - Central European Time(CET)'),
      ('Irish Standard Time(UTC+01)', 'UTC+01 - Irish Standard Time(IST)'),
      ('Middle European Time(UTC+01)', 'UTC+01 - Middle European Time(MET)'),
      ('West Africa Time(UTC+01)', 'UTC+01 - West Africa Time(WAT)'),
      ('Western European Summer Time(UTC+01)', 'UTC+01 - Western European Summer Time(WEST)'),
      ('Central Africa Time(UTC+02)', 'UTC+02 - Central Africa Time(CAT)'),
      ('Central European Summer Time(UTC+02)', 'UTC+02 - Central European Summer Time(CEST)'),
      ('Eastern European Time(UTC+02)', 'UTC+02 - Eastern European Time(EET)'),
      ('Central Europian Summer Time(UTC+02)', 'UTC+02 - Central Europian Summer Time(CEST)'),
      ('Israel Standard Time(UTC+02)', 'UTC+02 - Israel Standard Time(IST)'),
      ('Kaliningrad Time(UTC+02)', 'UTC+02 - Kaliningrad Time(KALT)'),
      ('Middle European Summer Time(UTC+02)', 'UTC+02 - Middle European Summer Time(MEST)'),
      ('South African Standard Time(UTC+02)', 'UTC+02 - South African Standard Time(SAST)'),
      ('West Africa Summer Time(UTC+02)', 'UTC+02 - West Africa Summer Time(WAST)'),
      ('Arabia Standard Time(UTC+03)', 'UTC+03 - Arabia Standard Time(AST)'),
      ('East Africa Time(UTC+03)', 'UTC+03 - East Africa Time(EAT)'),
      ('Eastern European Summer Time(UTC+03)', 'UTC+03 - Eastern European Summer Time(EEST)'),
      ('Israel Daylight Time(UTC+03)', 'UTC+03 - Israel Daylight Time(IDT)'),
      ('Indian Ocean Time(UTC+03)', 'UTC+03 - Indian Ocean Time(IOT)'),
      ('Moscow Time(UTC+03)', 'UTC+03 - Moscow Time(MSK)'),
      ('Showa Station Time(UTC+03)', 'UTC+03 - Showa Station Time(SYOT)'),
      ('Turkey Time(UTC+03)', 'UTC+03 - Turkey Time(TRT)'),
      ('Iran Standard Time(UTC+03:30)', 'UTC+03:30 - Iran Standard Time(IRST)'),
      ('Armenia Time(UTC+04)', 'UTC+04 - Armenia Time(AMT)'),
      ('Azerbaijan Time(UTC+04)', 'UTC+04 - Azerbaijan Time(AZT)'),
      ('Georgia Standard Time(UTC+04)', 'UTC+04 - Georgia Standard Time(GET)'),
      ('Gulf Standard Time(UTC+04)', 'UTC+04 - Gulf Standard Time(GST)'),
      ('Mauritius Time(UTC+04)', 'UTC+04 - Mauritius Time(MUT)'),
      ('Réunion Time(UTC+04)', 'UTC+04 - Réunion Time(RET)'),
      ('Samara Time(UTC+04)', 'UTC+04 - Samara Time(SAMT)'),
      ('Seychelles Time(UTC+04)', 'UTC+04 - Seychelles Time(SCT)'),
      ('Volgograd Time(UTC+04)', 'UTC+04 - Volgograd Time(VOLT)'),
      ('Afghanistan Time(UTC+04:30)', 'UTC+04:30 - Afghanistan Time(AFT)'),
      ('Iran Daylight Time(UTC+04:30)', 'UTC+04:30 - Iran Daylight Time(IRDT)'),
      ('Aqtobe Time(UTC+05)', 'UTC+05 - Aqtobe Time(AQTT)'),
      ('Heard and McDonald Islands Time(UTC+05)', 'UTC+05 - Heard and McDonald Islands Time(HMT)'),
      ('Mawson Station Time(UTC+05)', 'UTC+05 - Mawson Station Time(MAWT)'),
      ('Maldives Time(UTC+05)', 'UTC+05 - Maldives Time(MVT)'),
      ('Oral Time(UTC+05)', 'UTC+05 - Oral Time(ORAT)'),
      ('Pakistan Standard Time(UTC+05)', 'UTC+05 - Pakistan Standard Time(PKT)'),
      ('French Southern and Antarctic Time(UTC+05)', 'UTC+05 - French Southern and Antarctic Time(TFT)'),
      ('Tajikistan Time(UTC+05)', 'UTC+05 - Tajikistan Time(TJT)'),
      ('Turkmenistan Time(UTC+05)', 'UTC+05 - Turkmenistan Time(TMT)'),
      ('Uzbekistan Time(UTC+05)', 'UTC+05 - Uzbekistan Time(UZT)'),
      ('Yekaterinburg Time(UTC+05)', 'UTC+05 - Yekaterinburg Time(YEKT)'),
      ('Indian Standard Time(UTC+05:30)', 'UTC+05:30 - Indian Standard Time(IST)'),
      ('Sri Lanka Standard Time(UTC+05:30)', 'UTC+05:30 - Sri Lanka Standard Time(SLST)'),
      ('Nepal Time(UTC+05:45)', 'UTC+05:45 - Nepal Time(NPT)'),
      ('Alma-Ata Time(UTC+06)', 'UTC+06 - Alma-Ata Time(ALMT)'),
      ('British Indian Ocean Time(UTC+06)', 'UTC+06 - British Indian Ocean Time(BIOT)'),
      ('Bangladesh Standard Time(UTC+06)', 'UTC+06 - Bangladesh Standard Time(BST)'),
      ('Bhutan Time(UTC+06)', 'UTC+06 - Bhutan Time(BTT)'),
      ('Kyrgyzstan Time(UTC+06)', 'UTC+06 - Kyrgyzstan Time(KGT)'),
      ('Omsk Time(UTC+06)', 'UTC+06 - Omsk Time(OMST)'),
      ('Vostok Station Time(UTC+06)', 'UTC+06 - Vostok Station Time(VOST)'),
      ('Cocos Islands Time(UTC+06:30)', 'UTC+06:30 - Cocos Islands Time(CCT)'),
      ('Myanmar Standard Time(UTC+06:30)', 'UTC+06:30 - Myanmar Standard Time(MMT)'),
      ('Christmas Island Time(UTC+07)', 'UTC+07 - Christmas Island Time(CXT)'),
      ('Davis Time(UTC+07)', 'UTC+07 - Davis Time(DAVT)'),
      ('Hovd Time(UTC+07)', 'UTC+07 - Hovd Time(HOVT)'),
      ('Indochina Time(UTC+07)', 'UTC+07 - Indochina Time(ICT)'),
      ('Krasnoyarsk Time(UTC+07)', 'UTC+07 - Krasnoyarsk Time(KRAT)'),
      ('Novosibirsk Time (UTC+07)', 'UTC+07 - Novosibirsk Time (NOVT)'),
      ('Thailand Standard Time(UTC+07)', 'UTC+07 - Thailand Standard Time(THA)'),
      ('Western Indonesian Time(UTC+07)', 'UTC+07 - Western Indonesian Time(WIB)'),
      ('Australian Western Standard Time(UTC+08)', 'UTC+08 - Australian Western Standard Time(AWST)'),
      ('Brunei Time(UTC+08)', 'UTC+08 - Brunei Time(BDT)'),
      ('Choibalsan Standard Time(UTC+08)', 'UTC+08 - Choibalsan Standard Time(CHOT)'),
      ('Central Indonesia Time(UTC+08)', 'UTC+08 - Central Indonesia Time(WITA)'),
      ('China Standard Time(UTC+08)', 'UTC+08 - China Standard Time(CST)'),
      ('Hong Kong Time(UTC+08)', 'UTC+08 - Hong Kong Time(HKT)'),
      ('Irkutsk Time(UTC+08)', 'UTC+08 - Irkutsk Time(IRKT)'),
      ('Malaysia Standard Time(UTC+08)', 'UTC+08 - Malaysia Standard Time(MST)'),
      ('Malaysia Time(UTC+08)', 'UTC+08 - Malaysia Time(MYT)'),
      ('Philippine Time(UTC+08)', 'UTC+08 - Philippine Time(PHT)'),
      ('Philippine Standard Time(UTC+08)', 'UTC+08 - Philippine Standard Time(PST)'),
      ('Singapore Time(UTC+08)', 'UTC+08 - Singapore Time(SGT)'),
      ('Singapore Standard Time(UTC+08)', 'UTC+08 - Singapore Standard Time(SST)'),
      ('Ulaanbaatar Standard Time(UTC+08)', 'UTC+08 - Ulaanbaatar Standard Time(ULAT)'),
      ('Western Standard Time(UTC+08)', 'UTC+08 - Western Standard Time(WST)'),
      ('Choibalsan Summer Time(UTC+09)', 'UTC+09 - Choibalsan Summer Time(CHOST)'),
      ('Eastern Indonesian Time(UTC+09)', 'UTC+09 - Eastern Indonesian Time(WIT)'),
      ('Japan Standard Time(UTC+09)', 'UTC+09 - Japan Standard Time(JST)'),
      ('Korea Standard Time(UTC+09)', 'UTC+09 - Korea Standard Time(KST)'),
      ('Timor Leste Time(UTC+09)', 'UTC+09 - Timor Leste Time(TLT)'),
      ('Ulaanbaatar Summer Time(UTC+09)', 'UTC+09 - Ulaanbaatar Summer Time(ULAST)'),
      ('Yakutsk Time(UTC+09)', 'UTC+09 - Yakutsk Time(YAKT)'),
      ('Australian Central Standard Time(UTC+09:30)', 'UTC+09:30 - Australian Central Standard Time(ACST)'),
      ('Australian Eastern Standard Time(UTC+10)', 'UTC+10 - Australian Eastern Standard Time(AEST)'),
      ('Chamorro Standard Time(UTC+10)', 'UTC+10 - Chamorro Standard Time(CHST)'),
      ('Chuuk Time(UTC+10)', 'UTC+10 - Chuuk Time(CHUT)'),
      ('"Dumont dUrville Time"(UTC+10)', 'UTC+10 - "Dumont dUrville Time"(DDUT)'),
      ('Papua New Guinea Time(UTC+10)', 'UTC+10 - Papua New Guinea Time(PGT)'),
      ('Vladivostok Time(UTC+10)', 'UTC+10 - Vladivostok Time(VLAT)'),
      ('Australian Eastern Time(UTC+10|UTC+11)', 'UTC+10|UTC+11 - Australian Eastern Time(AET)'),
      ('Australian Central Daylight Saving Time(UTC+10:30)', 'UTC+10:30 - Australian Central Daylight Saving Time(ACDT)'),
      ('Lord Howe Standard Time(UTC+10:30)', 'UTC+10:30 - Lord Howe Standard Time(LHST)'),
      ('Australian Eastern Daylight Saving Time(UTC+11)', 'UTC+11 - Australian Eastern Daylight Saving Time(AEDT)'),
      ('Bougainville Standard Time(UTC+11)', 'UTC+11 - Bougainville Standard Time(BST)'),
      ('Kosrae Time(UTC+11)', 'UTC+11 - Kosrae Time(KOST)'),
      ('Lord Howe Summer Time(UTC+11)', 'UTC+11 - Lord Howe Summer Time(LHST)'),
      ('Macquarie Island Station Time(UTC+11)', 'UTC+11 - Macquarie Island Station Time(MIST)'),
      ('New Caledonia Time(UTC+11)', 'UTC+11 - New Caledonia Time(NCT)'),
      ('Norfolk Island Time(UTC+11)', 'UTC+11 - Norfolk Island Time(NFT)'),
      ('Pohnpei Standard Time(UTC+11)', 'UTC+11 - Pohnpei Standard Time(PONT)'),
      ('Sakhalin Island Time(UTC+11)', 'UTC+11 - Sakhalin Island Time(SAKT)'),
      ('Solomon Islands Time(UTC+11)', 'UTC+11 - Solomon Islands Time(SBT)'),
      ('Srednekolymsk Time(UTC+11)', 'UTC+11 - Srednekolymsk Time(SRET)'),
      ('Vanuatu Time(UTC+11)', 'UTC+11 - Vanuatu Time(VUT)'),
      ('Anadyr Time(UTC+12)', 'UTC+12 - Anadyr Time(ANAT)'),
      ('Fiji Time(UTC+12)', 'UTC+12 - Fiji Time(FJT)'),
      ('Gilbert Island Time(UTC+12)', 'UTC+12 - Gilbert Island Time(GILT)'),
      ('Magadan Time(UTC+12)', 'UTC+12 - Magadan Time(MAGT)'),
      ('Marshall Islands Time(UTC+12)', 'UTC+12 - Marshall Islands Time(MHT)'),
      ('New Zealand Standard Time(UTC+12)', 'UTC+12 - New Zealand Standard Time(NZST)'),
      ('Kamchatka Time(UTC+12)', 'UTC+12 - Kamchatka Time(PETT)'),
      ('Tuvalu Time(UTC+12)', 'UTC+12 - Tuvalu Time(TVT)'),
      ('Wake Island Time(UTC+12)', 'UTC+12 - Wake Island Time(WAKT)'),
      ('Chatham Standard Time(UTC+12:45)', 'UTC+12:45 - Chatham Standard Time(CHAST)'),
      ('New Zealand Daylight Time(UTC+13)', 'UTC+13 - New Zealand Daylight Time(NZDT)'),
      ('Phoenix Island Time(UTC+13)', 'UTC+13 - Phoenix Island Time(PHOT)'),
      ('Tokelau Time(UTC+13)', 'UTC+13 - Tokelau Time(TKT)'),
      ('Tonga Time(UTC+13)', 'UTC+13 - Tonga Time(TOT)'),
      ('Chatham Daylight Time(UTC+13:45)', 'UTC+13:45 - Chatham Daylight Time(CHADT)'),
      ('Line Islands Time(UTC+14)', 'UTC+14 - Line Islands Time(LINT)'),
 )