# Generated by Django 2.1.15 on 2021-01-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('job_category', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=56)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.TextField(blank=True)),
                ('job_link', models.URLField(blank=True, verbose_name='Job Posting Link')),
                ('company_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
