# Generated by Django 2.1.15 on 2020-08-08 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(choices=[('ASRG-S', 'ASRG-S'), ('ASRG-D', 'ASRG-D'), ('ASRG-TLV', 'ASRG-TLV'), ('ASRG-C', 'ASRG-C'), ('ASRG-SIN', 'ASRG-SIN'), ('ASRG-MUC', 'ASRG-MUC'), ('ASRG-CAI', 'ASRG-CAI'), ('ASRG-SHA', 'ASRG-SHA'), ('ASRG-BER', 'ASRG-BER'), ('ASRG-PIT', 'ASRG-PIT'), ('ASRG-SFO', 'ASRG-SFO'), ('ASRG-FRA', 'ASRG-FRA'), ('ASRG-JPN', 'ASRG-JPN'), ('ASRG-OXF', 'ASRG-OXF'), ('ASRG-SYD', 'ASRG-SYD'), ('ASRG-IASI', 'ASRG-IASI'), ('ASRG-DNCR', 'ASRG-DNCR'), ('ASRG-DAY', 'ASRG-DAY'), ('ASRG-REC', 'ASRG-REC'), ('ASRG-BLR', 'ASRG-BLR'), ('ASRG-LAX', 'ASRG-LAX'), ('ASRG-BUC', 'ASRG-BUC'), ('ASRG-QRO', 'ASRG-QRO'), ('ASRG-CGN', 'ASRG-CGN'), ('ASRG-TOR', 'ASRG-TOR'), ('ASRG-WIN', 'ASRG-WIN'), ('ASRG-KER', 'ASRG-KER'), ('ASRG-VIE', 'ASRG-VIE'), ('ASRG-HYD', 'ASRG-HYD')], default=('ASRG-S', 'ASRG-S'), max_length=24)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('ASRG_member', 'ASRG_member'), ('ASRG_global_lead', 'ASRG_global_lead'), ('ASRG_global_admin', 'ASRG_global_admin'), ('ASRG_sponsor_L1', 'ASRG_sponsor_L1'), ('ASRG_sponsor_L2', 'ASRG_sponsor_L2'), ('ASRG_sponsor_L3', 'ASRG_sponsor_L3'), ('ASRG_asip_contributor', 'ASRG_asip_contributor'), ('ASRG_S', 'ASRG_S'), ('ASRG_local_lead_S', 'ASRG_local_lead_S'), ('ASRG_D', 'ASRG_D'), ('ASRG_local_lead_D', 'ASRG_local_lead_D'), ('ASRG_TLV', 'ASRG_TLV'), ('ASRG_local_lead_TLV', 'ASRG_local_lead_TLV'), ('ASRG_C', 'ASRG_C'), ('ASRG_local_lead_C', 'ASRG_local_lead_C'), ('ASRG_SIN', 'ASRG_SIN'), ('ASRG_local_lead_SIN', 'ASRG_local_lead_SIN'), ('ASRG_MUC', 'ASRG_MUC'), ('ASRG_local_lead_MUC', 'ASRG_local_lead_MUC'), ('ASRG_CAI', 'ASRG_CAI'), ('ASRG_local_lead_CAI', 'ASRG_local_lead_CAI'), ('ASRG_SHA', 'ASRG_SHA'), ('ASRG_local_lead_SHA', 'ASRG_local_lead_SHA'), ('ASRG_BER', 'ASRG_BER'), ('ASRG_local_lead_BER', 'ASRG_local_lead_BER'), ('ASRG_PIT', 'ASRG_PIT'), ('ASRG_local_lead_PIT', 'ASRG_local_lead_PIT'), ('ASRG_SFO', 'ASRG_SFO'), ('ASRG_local_lead_SFO', 'ASRG_local_lead_SFO'), ('ASRG_FRA', 'ASRG_FRA'), ('ASRG_local_lead_FRA', 'ASRG_local_lead_FRA'), ('ASRG_JPN', 'ASRG_JPN'), ('ASRG_local_lead_JPN', 'ASRG_local_lead_JPN'), ('ASRG_OXF', 'ASRG_OXF'), ('ASRG_local_lead_OXF', 'ASRG_local_lead_OXF'), ('ASRG_SYD', 'ASRG_SYD'), ('ASRG_local_lead_SYD', 'ASRG_local_lead_SYD'), ('ASRG_IASI', 'ASRG_IASI'), ('ASRG_local_lead_IASI', 'ASRG_local_lead_IASI'), ('ASRG_DNCR', 'ASRG_DNCR'), ('ASRG_local_lead_DNCR', 'ASRG_local_lead_DNCR'), ('ASRG_DAY', 'ASRG_DAY'), ('ASRG_local_lead_DAY', 'ASRG_local_lead_DAY'), ('ASRG_REC', 'ASRG_REC'), ('ASRG_local_lead_REC', 'ASRG_local_lead_REC'), ('ASRG_BLR', 'ASRG_BLR'), ('ASRG_local_lead_BLR', 'ASRG_local_lead_BLR'), ('ASRG_LAX', 'ASRG_LAX'), ('ASRG_local_lead_LAX', 'ASRG_local_lead_LAX'), ('ASRG_BUC', 'ASRG_BUC'), ('ASRG_local_lead_BUC', 'ASRG_local_lead_BUC'), ('ASRG_QRO', 'ASRG_QRO'), ('ASRG_local_lead_QRO', 'ASRG_local_lead_QRO'), ('ASRG_CGN', 'ASRG_CGN'), ('ASRG_local_lead_CGN', 'ASRG_local_lead_CGN'), ('ASRG_TOR', 'ASRG_TOR'), ('ASRG_local_lead_TOR', 'ASRG_local_lead_TOR'), ('ASRG_WIN', 'ASRG_WIN'), ('ASRG_local_lead_WIN', 'ASRG_local_lead_WIN'), ('ASRG_KER', 'ASRG_KER'), ('ASRG_local_lead_KER', 'ASRG_local_lead_KER'), ('ASRG_VIE', 'ASRG_VIE'), ('ASRG_local_lead_VIE', 'ASRG_local_lead_VIE'), ('ASRG_HYD', 'ASRG_HYD'), ('ASRG_local_lead_HYD', 'ASRG_local_lead_HYD')],
            },
        ),
    ]
