# Generated by Django 2.1.15 on 2020-08-23 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='foundation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
