# Generated by Django 2.1.15 on 2020-09-06 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200823_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='location',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='user',
            name='chapter',
            field=models.ManyToManyField(related_name='users', to='authentication.Chapter'),
        ),
    ]
