# Generated by Django 2.1.15 on 2020-09-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200906_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='chapter',
            field=models.ManyToManyField(related_name='user', to='authentication.Chapter'),
        ),
    ]
