# Generated by Django 2.1.15 on 2020-08-18 19:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200818_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='foundation',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 18, 19, 1, 59, 50149, tzinfo=utc)),
        ),
    ]
