# Generated by Django 2.1.15 on 2020-08-18 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200819_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='foundation',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 18, 23, 45, 26, 112727, tzinfo=utc)),
        ),
    ]
