# Generated by Django 2.1.15 on 2020-08-18 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200819_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='foundation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 23, 55, 13, 470626, tzinfo=utc)),
        ),
    ]
