# Generated by Django 2.1.15 on 2020-08-19 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20200819_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='foundation',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 19, 0, 48, 3, 458412, tzinfo=utc)),
        ),
    ]
