# Generated by Django 2.1.15 on 2020-08-19 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20200819_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='foundation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 19, 0, 49, 47, 25027, tzinfo=utc)),
        ),
    ]
