# Generated by Django 2.1.15 on 2020-08-19 00:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20200819_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='foundation',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 0, 50, 39, 734543, tzinfo=utc)),
        ),
    ]
