# Generated by Django 2.1.15 on 2020-08-19 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20200819_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='foundation',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 19, 2, 2, 35, 172028, tzinfo=utc)),
        ),
    ]
