# Generated by Django 2.1.15 on 2020-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('presenter', models.CharField(max_length=120)),
                ('presenter_company', models.CharField(max_length=120)),
                ('presenter_info', models.TextField(blank=True)),
                ('present_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('job_category', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=56)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.TextField(blank=True)),
            ],
        ),
    ]
