# Generated by Django 2.1.15 on 2020-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_jobposting_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
